baseURL = 'https://ccyoasobi.github.io/blog/'
languageCode = 'en-us'
title = 'CC Yoasobi'
theme = 'PaperMod'

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"
